// Generated by gencpp from file your_package/Data.msg
// DO NOT EDIT!


#ifndef YOUR_PACKAGE_MESSAGE_DATA_H
#define YOUR_PACKAGE_MESSAGE_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace your_package
{
template <class ContainerAllocator>
struct Data_
{
  typedef Data_<ContainerAllocator> Type;

  Data_()
    : name()
    , id(0)  {
    }
  Data_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int64_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::your_package::Data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::your_package::Data_<ContainerAllocator> const> ConstPtr;

}; // struct Data_

typedef ::your_package::Data_<std::allocator<void> > Data;

typedef boost::shared_ptr< ::your_package::Data > DataPtr;
typedef boost::shared_ptr< ::your_package::Data const> DataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::your_package::Data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::your_package::Data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::your_package::Data_<ContainerAllocator1> & lhs, const ::your_package::Data_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::your_package::Data_<ContainerAllocator1> & lhs, const ::your_package::Data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace your_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::your_package::Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::your_package::Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::your_package::Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::your_package::Data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::your_package::Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::your_package::Data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::your_package::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da518bdae7932c5a0d1b2af3b1564e87";
  }

  static const char* value(const ::your_package::Data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda518bdae7932c5aULL;
  static const uint64_t static_value2 = 0x0d1b2af3b1564e87ULL;
};

template<class ContainerAllocator>
struct DataType< ::your_package::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "your_package/Data";
  }

  static const char* value(const ::your_package::Data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::your_package::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int64 id\n"
;
  }

  static const char* value(const ::your_package::Data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::your_package::Data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::your_package::Data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::your_package::Data_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOUR_PACKAGE_MESSAGE_DATA_H
