// Generated by gencpp from file your_package/gohomeRequest.msg
// DO NOT EDIT!


#ifndef YOUR_PACKAGE_MESSAGE_GOHOMEREQUEST_H
#define YOUR_PACKAGE_MESSAGE_GOHOMEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace your_package
{
template <class ContainerAllocator>
struct gohomeRequest_
{
  typedef gohomeRequest_<ContainerAllocator> Type;

  gohomeRequest_()
    {
    }
  gohomeRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::your_package::gohomeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::your_package::gohomeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct gohomeRequest_

typedef ::your_package::gohomeRequest_<std::allocator<void> > gohomeRequest;

typedef boost::shared_ptr< ::your_package::gohomeRequest > gohomeRequestPtr;
typedef boost::shared_ptr< ::your_package::gohomeRequest const> gohomeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::your_package::gohomeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::your_package::gohomeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace your_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::your_package::gohomeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::your_package::gohomeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::your_package::gohomeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::your_package::gohomeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::your_package::gohomeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::your_package::gohomeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::your_package::gohomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::your_package::gohomeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::your_package::gohomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "your_package/gohomeRequest";
  }

  static const char* value(const ::your_package::gohomeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::your_package::gohomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::your_package::gohomeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::your_package::gohomeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gohomeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::your_package::gohomeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::your_package::gohomeRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // YOUR_PACKAGE_MESSAGE_GOHOMEREQUEST_H
