// Generated by gencpp from file your_package/gokitchen.msg
// DO NOT EDIT!


#ifndef YOUR_PACKAGE_MESSAGE_GOKITCHEN_H
#define YOUR_PACKAGE_MESSAGE_GOKITCHEN_H

#include <ros/service_traits.h>


#include <your_package/gokitchenRequest.h>
#include <your_package/gokitchenResponse.h>


namespace your_package
{

struct gokitchen
{

typedef gokitchenRequest Request;
typedef gokitchenResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gokitchen
} // namespace your_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::your_package::gokitchen > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::your_package::gokitchen&) { return value(); }
};

template<>
struct DataType< ::your_package::gokitchen > {
  static const char* value()
  {
    return "your_package/gokitchen";
  }

  static const char* value(const ::your_package::gokitchen&) { return value(); }
};


// service_traits::MD5Sum< ::your_package::gokitchenRequest> should match
// service_traits::MD5Sum< ::your_package::gokitchen >
template<>
struct MD5Sum< ::your_package::gokitchenRequest>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::gokitchen >::value();
  }
  static const char* value(const ::your_package::gokitchenRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::gokitchenRequest> should match
// service_traits::DataType< ::your_package::gokitchen >
template<>
struct DataType< ::your_package::gokitchenRequest>
{
  static const char* value()
  {
    return DataType< ::your_package::gokitchen >::value();
  }
  static const char* value(const ::your_package::gokitchenRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::your_package::gokitchenResponse> should match
// service_traits::MD5Sum< ::your_package::gokitchen >
template<>
struct MD5Sum< ::your_package::gokitchenResponse>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::gokitchen >::value();
  }
  static const char* value(const ::your_package::gokitchenResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::gokitchenResponse> should match
// service_traits::DataType< ::your_package::gokitchen >
template<>
struct DataType< ::your_package::gokitchenResponse>
{
  static const char* value()
  {
    return DataType< ::your_package::gokitchen >::value();
  }
  static const char* value(const ::your_package::gokitchenResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOUR_PACKAGE_MESSAGE_GOKITCHEN_H
