// Generated by gencpp from file your_package/subtractRequest.msg
// DO NOT EDIT!


#ifndef YOUR_PACKAGE_MESSAGE_SUBTRACTREQUEST_H
#define YOUR_PACKAGE_MESSAGE_SUBTRACTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace your_package
{
template <class ContainerAllocator>
struct subtractRequest_
{
  typedef subtractRequest_<ContainerAllocator> Type;

  subtractRequest_()
    : A(0)
    , B(0)  {
    }
  subtractRequest_(const ContainerAllocator& _alloc)
    : A(0)
    , B(0)  {
  (void)_alloc;
    }



   typedef int32_t _A_type;
  _A_type A;

   typedef int32_t _B_type;
  _B_type B;





  typedef boost::shared_ptr< ::your_package::subtractRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::your_package::subtractRequest_<ContainerAllocator> const> ConstPtr;

}; // struct subtractRequest_

typedef ::your_package::subtractRequest_<std::allocator<void> > subtractRequest;

typedef boost::shared_ptr< ::your_package::subtractRequest > subtractRequestPtr;
typedef boost::shared_ptr< ::your_package::subtractRequest const> subtractRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::your_package::subtractRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::your_package::subtractRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::your_package::subtractRequest_<ContainerAllocator1> & lhs, const ::your_package::subtractRequest_<ContainerAllocator2> & rhs)
{
  return lhs.A == rhs.A &&
    lhs.B == rhs.B;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::your_package::subtractRequest_<ContainerAllocator1> & lhs, const ::your_package::subtractRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace your_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::your_package::subtractRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::your_package::subtractRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::your_package::subtractRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::your_package::subtractRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::your_package::subtractRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::your_package::subtractRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::your_package::subtractRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "623c199892ad84e046e039a21a0e0c11";
  }

  static const char* value(const ::your_package::subtractRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x623c199892ad84e0ULL;
  static const uint64_t static_value2 = 0x46e039a21a0e0c11ULL;
};

template<class ContainerAllocator>
struct DataType< ::your_package::subtractRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "your_package/subtractRequest";
  }

  static const char* value(const ::your_package::subtractRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::your_package::subtractRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 A\n"
"int32 B\n"
;
  }

  static const char* value(const ::your_package::subtractRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::your_package::subtractRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
      stream.next(m.B);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct subtractRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::your_package::subtractRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::your_package::subtractRequest_<ContainerAllocator>& v)
  {
    s << indent << "A: ";
    Printer<int32_t>::stream(s, indent + "  ", v.A);
    s << indent << "B: ";
    Printer<int32_t>::stream(s, indent + "  ", v.B);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOUR_PACKAGE_MESSAGE_SUBTRACTREQUEST_H
