// Generated by gencpp from file your_package/subtract.msg
// DO NOT EDIT!


#ifndef YOUR_PACKAGE_MESSAGE_SUBTRACT_H
#define YOUR_PACKAGE_MESSAGE_SUBTRACT_H

#include <ros/service_traits.h>


#include <your_package/subtractRequest.h>
#include <your_package/subtractResponse.h>


namespace your_package
{

struct subtract
{

typedef subtractRequest Request;
typedef subtractResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct subtract
} // namespace your_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::your_package::subtract > {
  static const char* value()
  {
    return "7704a1e1ef958eda0d23af3533547bea";
  }

  static const char* value(const ::your_package::subtract&) { return value(); }
};

template<>
struct DataType< ::your_package::subtract > {
  static const char* value()
  {
    return "your_package/subtract";
  }

  static const char* value(const ::your_package::subtract&) { return value(); }
};


// service_traits::MD5Sum< ::your_package::subtractRequest> should match
// service_traits::MD5Sum< ::your_package::subtract >
template<>
struct MD5Sum< ::your_package::subtractRequest>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::subtract >::value();
  }
  static const char* value(const ::your_package::subtractRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::subtractRequest> should match
// service_traits::DataType< ::your_package::subtract >
template<>
struct DataType< ::your_package::subtractRequest>
{
  static const char* value()
  {
    return DataType< ::your_package::subtract >::value();
  }
  static const char* value(const ::your_package::subtractRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::your_package::subtractResponse> should match
// service_traits::MD5Sum< ::your_package::subtract >
template<>
struct MD5Sum< ::your_package::subtractResponse>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::subtract >::value();
  }
  static const char* value(const ::your_package::subtractResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::subtractResponse> should match
// service_traits::DataType< ::your_package::subtract >
template<>
struct DataType< ::your_package::subtractResponse>
{
  static const char* value()
  {
    return DataType< ::your_package::subtract >::value();
  }
  static const char* value(const ::your_package::subtractResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOUR_PACKAGE_MESSAGE_SUBTRACT_H
