// Generated by gencpp from file your_package/Sum.msg
// DO NOT EDIT!


#ifndef YOUR_PACKAGE_MESSAGE_SUM_H
#define YOUR_PACKAGE_MESSAGE_SUM_H

#include <ros/service_traits.h>


#include <your_package/SumRequest.h>
#include <your_package/SumResponse.h>


namespace your_package
{

struct Sum
{

typedef SumRequest Request;
typedef SumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Sum
} // namespace your_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::your_package::Sum > {
  static const char* value()
  {
    return "713e5cf1444846805670f946f08bfc96";
  }

  static const char* value(const ::your_package::Sum&) { return value(); }
};

template<>
struct DataType< ::your_package::Sum > {
  static const char* value()
  {
    return "your_package/Sum";
  }

  static const char* value(const ::your_package::Sum&) { return value(); }
};


// service_traits::MD5Sum< ::your_package::SumRequest> should match
// service_traits::MD5Sum< ::your_package::Sum >
template<>
struct MD5Sum< ::your_package::SumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::Sum >::value();
  }
  static const char* value(const ::your_package::SumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::SumRequest> should match
// service_traits::DataType< ::your_package::Sum >
template<>
struct DataType< ::your_package::SumRequest>
{
  static const char* value()
  {
    return DataType< ::your_package::Sum >::value();
  }
  static const char* value(const ::your_package::SumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::your_package::SumResponse> should match
// service_traits::MD5Sum< ::your_package::Sum >
template<>
struct MD5Sum< ::your_package::SumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::Sum >::value();
  }
  static const char* value(const ::your_package::SumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::SumResponse> should match
// service_traits::DataType< ::your_package::Sum >
template<>
struct DataType< ::your_package::SumResponse>
{
  static const char* value()
  {
    return DataType< ::your_package::Sum >::value();
  }
  static const char* value(const ::your_package::SumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOUR_PACKAGE_MESSAGE_SUM_H
